### ISSUE TITLE
KITTI

### ISSUE THREAD

**Issue by TimGor1997** [Cliu2/MTrans#10]
Dear author,
May I ask how to choose 500 frames and 125 frames of KITTI, is there have a split.txt?

**Comment by Cliu2** [comment]
Hi,

Thank you for the question. We simply choose the first 500/125 frames for training.

**Comment by TimGor1997** [comment]
Dear author,
Thank you for your reply！
Would like to ask, how to achieve 500/125 frame training PointPillars and PointRCNN? How do you change the OpenPCDet code? This will be of great help to me. Looking forward to your reply, thank you!

**Comment by TimGor1997** [comment]
Dear author,
I would like to ask how to use the 'pc2img' function in 'modality_mapper'? How do I get the parameter 'idx_map'?
亲爱的作者您好！
我想请教一下，文件‘modality_mapper.py’里面的函数‘pc2img’中，‘idx_map’这个参数是怎么产生的呢？这将对我有很大的帮助，希望您能赐教一下，衷心感谢您~




TimGor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cliu2/MTrans"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月15日(星期四) 中午12:40
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Cliu2/MTrans] KITTI (Issue #10)





 
Hi,
 
Thank you for the question. We simply choose the first 500/125 frames for training.
