### ISSUE TITLE
Missing batch size

### ISSUE THREAD

**Issue by smueleg** [Cliu2/MTrans#2]
`build_image_location_map` expects (B, H, W) while here only (H, W) are passed
https://github.com/Cliu2/MTrans/blob/7ce7935a6cfde1abdc46927d4dafd03a6c1f96b4/datasets/kitti_detection.py#L65
https://github.com/Cliu2/MTrans/blob/7ce7935a6cfde1abdc46927d4dafd03a6c1f96b4/models/MTrans.py#L173

**Comment by Cliu2** [comment]
@smueleg Hi, sorry there is a file version mismatch problem. The codes are updated. You should be able to run the script with the default config now.
