### ISSUE TITLE
Downloading the trained checkpoint requires a log in

### ISSUE THREAD

**Issue by smueleg** [Cliu2/MTrans#4]
I can't download the trained checkpoint from https://connecthkuhk-my.sharepoint.com/personal/lcon7_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Flcon7%5Fconnect%5Fhku%5Fhk%2FDocuments%2FMTrans%5Fckpt%2Fbest%5Fmodel%2Ept&parent=%2Fpersonal%2Flcon7%5Fconnect%5Fhku%5Fhk%2FDocuments%2FMTrans%5Fckpt&ga=1 as I am requested to log in

**Comment by Cliu2** [comment]
Hi, sorry that the previous link seems to be private to the organization. Please use the new link (https://connecthkuhk-my.sharepoint.com/:u:/g/personal/lcon7_connect_hku_hk/EYyRIedDNolHr3GSq0b3CZoBgsyI3XVjjtz4STD97WtKUQ?e=IhhNk4), it should be publicly available now. We also update the link in README.

To use the checkpoint, you can set the 'init_checkpoint' in the config .yaml file to be the path to your saved checkpoint.
