### ISSUE TITLE
I believe it's ECCV 2022...?

### ISSUE THREAD

**Issue by Rtakaha** [Cliu2/MTrans#8]
In README:
> The PyTorch implementation of [Multimodal Transformer for Automatic 3D Annotation and Object Detection](https://arxiv.org/abs/2207.09805), which has been accepted by ECCV2023.

I believe it should be ECCV 2022(https://dl.acm.org/doi/abs/10.1007/978-3-031-19839-7_38).
Not an essential issue but it's better to be corrected. Thank you!

**Comment by Cliu2** [comment]
Yes you are correct. Thank you for pointing that out. Will fix the README.
