### ISSUE TITLE
Where is the inference script present that can give me 3D annotations on point clouds?

### ISSUE THREAD

**Issue by ayaan-mphasis** [Cliu2/MTrans#9]

**Comment by Cliu2** [comment]
Hi, after you finish training the model with the script "train.py", you should have a checkpoint file. Then, you can generate labels as the following:

- Set `gen_label=True` in the config file
- Set `init_checkpoint` (i.e., the path to your trained model checkpoint) in the config file
- Specify `label_dir`, where the generated labels will be saved in the config file
- Rerun the "train.py" script with your new config file

You may want to comment out [Ln209-222](https://github.com/Cliu2/MTrans/blob/52e1b81def3ef19b4dded9d1f0faa5008b33e4ea/train.py#L209) in "trian.py" to skip repetitive training during generating labels.

**Comment by ayaan-mphasis** [comment]
Thanks! Can this be done for other datasets like Stanford Indoor Scenes(S3DIS) other than KITTI?

**Comment by Cliu2** [comment]
We haven't tried other datasets like S3DIS, so how would MTrans perform on S3DIS is not yet known, since indoor data are usually very different from outdoor scenes. However, you are welcome to try this method on other datasets like that :)
